version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: book_eat_nepal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  bandobasta:
    image: bandobasta  # Replace with your actual image name
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_eat_nepal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - '8080:8080'
