spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_eat_nepal
    username: postgres
    password: 6441
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    username: niranjanthapa6441@gmail.com
    password: password
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
    debug: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /book-eat-nepal/api/v1
  port: 8080
bandobasta:
  app:
    jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    jwtExpirationMs: 86400000
    jwtCookieName: bandobasta
