spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_eat_nepal
    username: postgres
    password: 6441
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: bandobastanepal@gmail.com
    password: wxhehpdcnglpdtft
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true
server:
  servlet:
    context-path: /bandobasta/api/v1
  port: 8080

bandobasta:
  app:
    jwtSecret: ======================Bandbobasta=Spring===========================
    jwtExpirationMs: 86400000
    jwtCookieName: bandobasta
