spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: bandobastanepal@gmail.com
    password: wxhehpdcnglpdtft
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true
server:
  servlet:
    context-path: /bandobasta/api/v1
  port: 8080

bandobasta:
  app:
    jwtSecret: ======================Bandbobasta=Spring===========================
    jwtExpirationMs: 86400000
    jwtCookieName: bandobasta
cloud:
  aws:
    credentials:
      accessKey: AKIAST6S635GKXOPTEUY
      secretKey: gOzGyTtn3VMITqhJfyOAxihM8aTA7bplWy7hVfWG
    region:
      static: ap-southeast-2  # Ensure this is the correct region for your S3 bucket
    s3:
      bucket: bandobasta-bucket

ServicePointManager:
  DefaultConnectionLimit: 25