INSERT INTO user_role(name) VALUES('ROLE_USER');
INSERT INTO user_role(name) VALUES('ROLE_MANAGEMENT');
INSERT INTO user_role(name) VALUES('ROLE_ADMIN');
INSERT INTO user_role(name) VALUES('ROLE_OWNER');

insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1999-12-02','niranjanthapa@gmail.com','Niranjan','Thapa','','$2a$10$d/4XH0CIbbUN0UtJhk7mT.jCFb/peVBIUgaQmg/G0Q2kkTQrBJUki','9810314784','ACTIVE',1,'niranjan','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('2000-12-20','robinkarki@gmail.com','Rabindra','Karki','Jung','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810314484','ACTIVB',2,'robin','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('2002-01-03','ravikhadka@gmail.com','Ravi','Khadka','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810313784','ACTIVE',4,'ravi','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('2000-10-12','prabeshkhati@gmail.com','Prabesh','Chettri','Khati','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810313284','ACTIVE',1,'prabesh','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1990-12-20','abhisekhKhadka@gmail.com','ABhisekh','Khadka','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810214384','ACTIVE',2,'abhisekh','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1991-11-20','prashannathapa@gmail.com','prashanna','Thapa','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9810224784','ACTIVE',4,'prashanna','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1992-10-20','nimasherpa@gmail.com','nima','sherpa','tsering','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814314484','ACTIVE',1,'tseringnima','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1993-09-20','nabinshiwakoti@gmail.com','nabin','shiwakoti','Khati','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814313284','ACTIVE',2,'nabin','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1994-02-20','nishanbade@gmail.com','nishan','bade','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814314784','ACTIVE',4,'nishan','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1995-05-20','rupashresthagmail.com','rupa','shrestha','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814313784','ACTIVE',4,'rupa','true','true');
insert into app_user (date_of_birth,email,first_name,last_name,middle_name,password,phone_number,status,role_id,username,enabled,locked)  values ('1996-01-20','sudikshyatwayana@gmail.com','sudikshya','twayana','','$2a$10$YfrGSaiDIaIcwWP78wsWiuTlwabcaO5BCPj.Iryf0m4XdidTTjaaK','9814214384','ACTIVE',1,'sudikshya','true','true');
