package com.example.BookEatNepal.Enums;

public enum FoodCategory {
    APPETIZER,
    SOUP,
    SALAD,
    MAIN_COURSE_VEGETARIAN,
    MAIN_COURSE_NON_VEGETARIAN,
    SIDE_DISH,
    BREAD,
    DESSERT,
    BEVERAGE_NON_ALCOHOLIC,
    BEVERAGE_ALCOHOLIC,
    SPECIALTY_ITEM,
    CONDIMENT,
    LIVE_STATION
}
